apiVersion: v1  
kind: Service  
metadata:
  name: my-drupal  
  namespace: drupal  
spec:
  type: LoadBalancer  
  ports:
    - port: 80  
      targetPort: 80  
  selector:
    app: my-drupal