apiVersion: v1  
kind: Service  
metadata:
  name: prometheus-server  
  namespace: monitoring  # Assurez-vous d'ajouter le namespace ici  
  labels:
    app: prometheus  
spec:
  type: LoadBalancer  
  ports:
    - port: 8088             # Port externe du LoadBalancer  
      targetPort: 9090     # Port interne sur lequel Prometheus écoute  
  selector:
    app: prometheus        # Assurez-vous que cela correspond aux labels de votre pod Prometheus



